### ISSUE TITLE
Index name too large in table 'bitbag_sylius_cms_plugin_frequently_asked_question_translation'

### ISSUE THREAD

**Issue by h3llr4iser** [BitBagCommerce/SyliusCmsPlugin#105]
I have a problem doing a migration:

[Doctrine\DBAL\Exception\DriverException]                                    
  An exception occurred while executing 'CREATE TABLE bitbag_sylius_cms_plugi  
  n_frequently_asked_question_translation (id INT AUTO_INCREMENT NOT NULL, tr  
  anslatable_id INT NOT NULL, question VARCHAR(1500) NOT NULL, answer LONGTEX  
  T NOT NULL, locale VARCHAR(255) NOT NULL, INDEX IDX_1F3306412C2AC5D3 (trans  
  latable_id), UNIQUE INDEX bitbag_sylius_cms_plugin_frequently_asked_questio  
  n_translation_uniq_trans (translatable_id, locale), PRIMARY KEY(id)) DEFAUL  
  T CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB':               
                                                                               
  SQLSTATE[42000]: Syntax error or access violation: 1059 Le nom de l'identif  
  icateur 'bitbag_sylius_cms_plugin_frequently_asked_question_translation_uni  
  q_trans' est trop long

**Comment by bitbager** [comment]
CC @shinoks,

Thanks! We tested it only on SQLite, so didn't notice it could be too long for MySQL. 

#106 PR should fix it.
