### ISSUE TITLE
Add WYSIWYG plugin for HTML type

### ISSUE THREAD

**Issue by gabiudrescu** [BitBagCommerce/SyliusCmsPlugin#120]
While watching the webinar from last week, I just realized that the HTML content block is missing a WYSIWYG form in admin to be more user friendly.

And from the implementation point of view, I guess this means:
 - add WYSIWYG bundle as a dependency to this plugin
 - change HtmlBlockTranslationType from `TextareaType::class` to `CKEditorType::class`

wdyt?

**Comment by bitbager** [comment]
We have inclued a customozation guide for it. We will probably add it to the core with a nice toggle switch for the WYSIWYG editor. Leaving it as opened, thanks!

**Comment by bitbager** [comment]
It's coming with the v2.0.0! 🎉

**Comment by gabiudrescu** [comment]
Maybe you can implement this WYSIWYG editor: https://github.com/yakovlevga/brickyeditor

I think it will be better, from user point of view, to be able to edit static blocks on the website like that. 

Or, if you plan to use CKEditor, maybe that one can also have the WYSIWYG feature enabled: https://sdk.ckeditor.com/samples/inline.html

**Comment by bitbager** [comment]
Hi @gabiudrescu. How does the editor differ from CKEditor? Actually, we already integrated CKEditor with the plugin due to easy to install FOSCKEditorBundle 🙁

**Comment by gabiudrescu** [comment]
brickyeditor is more friendly to inline editing right on the front end of the website.

you can pull the same with CKEditor though... but from what I learned, brickyeditor is better for such things. give it a try :)

**Comment by bitbager** [comment]
At this moment, we decided to use CKEditor. We will see how it goes in the future 🙂
