### ISSUE TITLE
Plugin does not support theming

### ISSUE THREAD

**Issue by bitbager** [BitBagCommerce/SyliusCmsPlugin#129]

**Comment by stefandoorn** [comment]
This is quite unhandy for me right now, as we have a theme that's being shared in multiple projects currently (but that does not seem to work for this plugin). Didn't figure out a solution yet, besides overriding the routing.

**Comment by bitbager** [comment]
Any updates on this issue? To be honest, I haven't thought yet about how to solve this problem.
