### ISSUE TITLE
Page Image mapping error

### ISSUE THREAD

**Issue by nicoplh** [BitBagCommerce/SyliusCmsPlugin#137]
Hi, it seems there is an error in the new mapping ?

[FAIL] The entity-class BitBag\SyliusCmsPlugin\Entity\PageImage mapping is invalid:
 * The association BitBag\SyliusCmsPlugin\Entity\PageImage#owner refers to the inverse side field BitBag\SyliusCmsPlugin\Entity\PageTranslation#image which does not exist.

**Comment by bitbager** [comment]
CC @antonioperic. Could you take a look at this issue?

**Comment by bitbager** [comment]
@antonioperic, have you maybe found some time for it?

**Comment by antonioperic** [comment]
@bitbager i will try this week. sorry busy to much

**Comment by antonioperic** [comment]
@nicoplh I cannot reproduce that bug. I tried in plugin standalone version and also inside our project. everything seems ok. if you can give more info, please
