### ISSUE TITLE
Possible bug in the "page" Sylius resource

### ISSUE THREAD

**Issue by johnkrovitch** [BitBagCommerce/SyliusCmsPlugin#140]
Hi,

I recently added the SyliusCmsPlugin to my project. It works well, thanks !

I have a problem when I try to search pages in the admin, and i got this error "[Semantical Error] line 0, col 155 near 'name LIKE '%test%'': Error: Class BitBag\SyliusCmsPlugin\Entity\Page has no field or association named type".

And when I check in this file https://github.com/BitBagCommerce/SyliusCmsPlugin/blob/master/src/Resources/config/grids/admin/page.yml , but the page does not seem to have a `type` field. Maybe it should be removed from the filters ?

**Comment by bitbager** [comment]
Indeed. It should be removed. May I ask you to provide a valid PR? 🙂

**Comment by johnkrovitch** [comment]
yes

**Comment by johnkrovitch** [comment]
PR https://github.com/BitBagCommerce/SyliusCmsPlugin/pull/141
