### ISSUE TITLE
HTML type block include image type block

### ISSUE THREAD

**Issue by jcgdjob** [BitBagCommerce/SyliusCmsPlugin#145]
Could HTML type block include image type block?
It would be great if it support such function.

**Comment by bitbager** [comment]
You mean nesting the `{{  bitbag_cms_render() }}` Twig function in the HTML block form in admin panel?

**Comment by jcgdjob** [comment]
Yes

**Comment by bitbager** [comment]
It should work now in the 2.0.0. Read https://github.com/BitBagCommerce/SyliusCmsPlugin/blob/master/doc/twig-functions-in-admin.md for more details.
