### ISSUE TITLE
Template var in render block code seems ignored

### ISSUE THREAD

**Issue by stefandoorn** [BitBagCommerce/SyliusCmsPlugin#149]
```
{{ render(path('bitbag_sylius_cms_plugin_shop_block_render', {'code' : 'homepage_header_image', 'template' : '@App/Some/Template/_path.html.twig'})) }}
```

I have the impression the `template` variable here is ignored, looking in `vendor/bitbag/cms-plugin/src/Controller/BlockController.php` the resolver always returns me the default type for HTML, as I can't find any code that takes in account the `template` variable set.

```
        $blockTemplateResolver = $this->get('bitbag_sylius_cms_plugin.resolver.block_template');
        $template = $blockTemplateResolver->resolveTemplate($block);
```

Always results into: `@BitBagSyliusCmsPlugin/Shop/Block/Show/htmlBlock.html.twig"`

Currently using v1.2, as I'm on Sylius v1.0 at the moment.

**Comment by stefandoorn** [comment]
Changing

```
$template = $blockTemplateResolver->resolveTemplate($block);
```

into

```
$template = $request->get('template') ?? $blockTemplateResolver->resolveTemplate($block);
```

Makes it work, not sure if that's the solution you want though, else I can PR it. Of course can also put it in the resolver, but that's just passing around variables in this case.

**Comment by patrick477** [comment]
Indeed. It should be added. May I ask you to provide a valid PR? :)

**Comment by stefandoorn** [comment]
As mentioned above or another solution?
