### ISSUE TITLE
Backport template fix to 1.2

### ISSUE THREAD

**Issue by stefandoorn** [BitBagCommerce/SyliusCmsPlugin#156]
@patrick477 Would it be possible to add this fix also in a 1.2.x release?

https://github.com/BitBagCommerce/SyliusCmsPlugin/commit/9a6d48a93d7cdb343c611c74fe7633c762d5d740

I'm migrating to this plugin, but cannot upgrade Sylius to 1.1 yet, but need this template fix so I can at least release the CMS migration, and then work on migrating to Sylius 1.1 & version 1.3 of this plugin :)

Thanks!

**Comment by patrick477** [comment]
yes, but now I do not have time for this, If you need it ASAP, you can do PR with a fix on branch `1.2.3` and I'll give you a tag update
