### ISSUE TITLE
Bundle tries to load its JS resources using invalid URL

### ISSUE THREAD

**Issue by mikemix** [BitBagCommerce/SyliusCmsPlugin#161]
When I enter any form within this bundle (either block form or page form) bundle tries to load its JS resources using invalid URL:

1.
Page at:
http://localhost:8080/app_dev.php/admin/pages/new

Requested resources (with 404 error):
http://localhost:8080/bundles/_themes/[theme_name]/default/bitbagsyliuscmsplugin/js/bitbag-page-slug.js
http://localhost:8080/bundles/_themes/[theme_name]/default/bitbagsyliuscmsplugin/js/bitbag-page-slug.js

2.
Page at:
http://localhost:8080/app_dev.php/admin/blocks/new/image

Requested resources (with 404 error):
http://localhost:8080/bundles/_themes/[theme_name]/default/bitbagsyliuscmsplugin/js/bitbag-block-image-preview.js
http://localhost:8080/bundles/_themes/[theme_name]/default/bitbagsyliuscmsplugin/js/bitbag-block-image-preview.js

Yep, both are requested twice lol. The base path for the resources should be: `/bundles`. This is my directory structure:

![Directory structure](https://user-images.githubusercontent.com/2399452/41901333-eabefb44-7930-11e8-8093-4312e5791782.png)

I'm using:

```
        "php": "^7.1",
        "bitbag/cms-plugin": "^1.3",
        "sylius/sylius": "1.2.*",
        "symfony/symfony": "^3.4|^4.1"
```

**Comment by mikemix** [comment]
This is how: `Sylius\Bundle\ThemeBundle\Asset\Package\PathPackage` works. If requested asset is not an absolute path, it merges the path with the theme context if one is set:

```
        if ($this->isAbsoluteUrl($path)) {
            return $path;
        }

        $theme = $this->themeContext->getTheme();
        if (null !== $theme) {
            $path = $this->pathResolver->resolve($path, $theme);
        }
```

**Comment by mikemix** [comment]
My bad :D :dagger:

**Comment by bitbager** [comment]
Anyway, thanks for the information. There were many people in the community that had problems with theming in this plugin. CC @patrick477.

**Comment by mikemix** [comment]
Well the `sylius:theme:assets:install` has to be called.

**Comment by bitbager** [comment]
We will mention it in the README. Thanks!
