### ISSUE TITLE
node_modules symlink in vendor breaks vagrant rsync

### ISSUE THREAD

**Issue by tdestro** [BitBagCommerce/SyliusCmsPlugin#162]
broken symlink node_modules in vendor upsets rsync during vagrant up.

There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /Users/*username*/sylius/
Guest path: /vagrant
Command: "rsync" "--verbose" "--archive" "--delete" "-z" "--copy-links" "--no-owner" "--no-group" "--rsync-path" "sudo rsync" "-e" "ssh -p 2222 -o LogLevel=FATAL  -o ControlMaster=auto -o ControlPath=/var/folders/ny/6szphdgs1nb76sgc4p7kmz400000gn/T/ssh.236 -o ControlPersist=10m  -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i '/Users/*username*/sylius/.vagrant/machines/sylius/virtualbox/private_key'" "--exclude" ".vagrant/" "/Users/*username*/sylius/" "vagrant@127.0.0.1:/vagrant"
Error: symlink has no referent: "/Users/*username*/sylius/sites/Sylius/vendor/bitbag/cms-plugin/node_modules"
rsync error: some files could not be transferred (code 23) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-52/rsync/main.c(996) [sender=2.6.9]

**Comment by bitbager** [comment]
Unfortunately, we have not tested this plugin with Vagrant.

I believe this is a problem of Sylius plugin skeleton. 

CC: @pamil, @Zales0123
