### ISSUE TITLE
Bug in service declaration

### ISSUE THREAD

**Issue by muldos** [BitBagCommerce/SyliusCmsPlugin#165]
Hi, I've just upgraded to 2.0, and I've seen that ajax call to search products fail.
It seems to be a missing "public: true" declaration missing for the service 
bitbag_sylius_cms_plugin.controller.action.admin.product_search

![capture d ecran 2018-07-05 a 14 20 13](https://user-images.githubusercontent.com/849186/42323082-2fa6ea2a-805f-11e8-82af-15d8093b6551.png)

![capture d ecran 2018-07-05 a 14 24 24](https://user-images.githubusercontent.com/849186/42323106-440676fc-805f-11e8-8b47-cdb95d7f3cf4.png)

Best regards,

David

**Comment by bitbager** [comment]
Should be fixed now. Thanks!
