### ISSUE TITLE
Bug in preview : missing service or alias

### ISSUE THREAD

**Issue by muldos** [BitBagCommerce/SyliusCmsPlugin#166]
Hi,
I've just upgraded to 2.0 and I've got an error when I preview a block 

![capture d ecran 2018-07-05 a 14 20 33](https://user-images.githubusercontent.com/849186/42323195-97a6db94-805f-11e8-959c-e6b0d0fabbd5.png)

Maybe all these resolver services need a `public : true` declaration in resolver.yml ?
![capture d ecran 2018-07-05 a 14 30 16](https://user-images.githubusercontent.com/849186/42323316-0fd22358-8060-11e8-9d43-5fa86c921b98.png)

Best regards,

David

**Comment by bitbager** [comment]
Hi. Thanks for reporting the bug. 2.0 is not stable yet, we will release a tested version soon.

**Comment by bitbager** [comment]
Should be fixed in #773fabd.
