### ISSUE TITLE
Sitemap no more optional in 2.0 ?

### ISSUE THREAD

**Issue by wadjeroudi** [BitBagCommerce/SyliusCmsPlugin#168]
With this commit https://github.com/BitBagCommerce/SyliusCmsPlugin/commit/5a651cb5e72528e3669b1ab770cf9bbcf02fe8ab
in 2.0, the sitemap is always defined, so if you don't have the sylius sitemap plugin it will fire an error : 
```
  The service "bitbag_sylius_cms_plugin.sitemap_provider.page" has a dependency on a non-existent service "sylius.sitemap_url_factory".  
```

Is it a mistake ? @bitbager

**Comment by bitbager** [comment]
In 2.0 CMS will use the Sitemap plugin by default. We will mention it in the README.
