### ISSUE TITLE
doctrine schema update 

### ISSUE THREAD

**Issue by Fed0t** [BitBagCommerce/SyliusCmsPlugin#173]
`bin/console doctrine:schema:update --force`
 no migrations detected :)
Message:
` [OK] Nothing to update - your database is already in sync with the current entity metadata. `

prod.log output:
`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'techbuy.bitbag_cms_block' doesn't exist `

**Comment by bitbager** [comment]
Seems like you have problems with environments. Read this - https://symfony.com/doc/current/configuration/environments.html.
