### ISSUE TITLE
Unable to generate a URL for the named route

### ISSUE THREAD

**Issue by KriBetko** [BitBagCommerce/SyliusCmsPlugin#181]
Have error after update from ^1.3 to ^2.0 on _/admin_ route:
> An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "bitbag_sylius_cms_plugin_admin_media_index" as such route does not exist.").

How fix?

**Comment by bitbager** [comment]
Have you cleared your cache? This route should be generated with SyliusResourceBundle, perhaps the Symfony container needs to be flushed after the update.

**Comment by KriBetko** [comment]
It's works. Thanks!
