### ISSUE TITLE
Separate into CMS component and bundle

### ISSUE THREAD

**Issue by loic425** [BitBagCommerce/SyliusCmsPlugin#187]
A sylius plugin depends on "sylius/sylius". I'd like to use it on projects using sylius bundles and components. So it could be very interesting to separate it into a component and a symfony bundle:

- **BitBagCommerce/SyliusCmsComponent**: php components
- **BitBagCommerce/SyliusCmsBundle**: symfony integration
- **BitBagCommerce/SyliusCmsPlugin**: sylius core integration

**Comment by bitbager** [comment]
We've been thinking about it, however, there are many great CMS solutions for Symfony on GitHub. If we get a feedback from the community saying that there's a need for such architecture, we might consider it. To be honest, so far you're the first person coming to us with such idea 🙂
