### ISSUE TITLE
Create a new page About in the Sylius

### ISSUE THREAD

**Issue by KarlMakri** [BitBagCommerce/SyliusCmsPlugin#189]
Hi, 

When I want to configure About content on the panel Admin Sylius.

I have filled all the fields.

And with this code in the twig footer : 

href="{{ path('bitbag_sylius_cms_plugin_shop_page_show', {'slug' : 'about'}) }}" 

class="item">{{ 'sylius.ui.about'|trans }}

 In the moment of the save of the page About in the panel admin Sylius, I have this error message:

An exception occurred while executing 'INSERT INTO bitbag_cms_page_image (type, path, owner_id) VALUES (?, ?, ?)' with params ["about", null, 7]:

SQLSTATE[23000]: Integrity constraint violation: 1048 Le champ 'path' ne peut être vide (null)

And this message on the Logs in the Symfony : 

INFO14:52:35 | php | User Deprecated: The "Sylius\Component\User\Model\UserInterface" interface extends "Symfony\Component\Security\Core\User\AdvancedUserInterface" that is deprecated since Symfony 4.1 *.
-- | -- | --

If you have a suggestion for resolver this problem i'll be taker.

Thank you for you help.

**Comment by bitbager** [comment]
It seems like your internal problem with your local environment. From our side, creating pages works fine.
