### ISSUE TITLE
Invalid mapping

### ISSUE THREAD

**Issue by nicoplh** [BitBagCommerce/SyliusCmsPlugin#191]
Hi, 

i've made the upgrade of your plugin, from 1.2 to 2.1 and and it shows this invalid entity mapping : 

The association BitBag\SyliusCmsPlugin\Entity\PageImage#owner refers to the inverse side field BitBag\SyliusCmsPlugin\Entity\PageTranslation#image which does not exist.

Do i have any change to do ? or is it your side ?

**Comment by bitbager** [comment]
Seems like this is an issue on our side. We will handle it. CC @damonsson, @patrick477.

**Comment by cyrosy** [comment]
I resolved this issue locally by modifying the `PageImage.orm.yml` mapping file, and updating the `targetEntity` of the `owner` one-to-one association to `BitBag\SyliusCmsPlugin\Entity\PageTranslationInterface`.
Would a PR help this to be fixed ?

**Comment by petrhamak** [comment]
cyrosy: I have same problem, what exactly have you edited? Thank you.

**Comment by petrhamak** [comment]
I have got it working with editing vendor as cyrosy has written.
I have tried to override class PageImage, but it doesn't work.

Any plan to fix the bug?

**Comment by cyrosy** [comment]
It seems that either #209 or #214 could resolve this.
I'll try to fix the build - I assume that is what prevent these MR from being merged
