### ISSUE TITLE
Service sylius.sitemap_url_factory not found

### ISSUE THREAD

**Issue by vgrdominik** [BitBagCommerce/SyliusCmsPlugin#193]
Error to update repository at versions >v1.3.6. A service not found.

> The service "bitbag_sylius_cms_plugin.sitemap_provider.page" has a dependency on a non-existent service "sylius.sitemap_url_factory".

This commit has a not exists service in sylius 1.1.6: https://github.com/BitBagCommerce/SyliusCmsPlugin/blob/633781f9ac2e098c950a45667fdc147a5c56ce3f/src/Resources/config/services/sitemap_provider.yml

**Comment by stefandoorn** [comment]
Which version are you on? I just upgraded to v1.4.2, seems to work.

**Comment by vgrdominik** [comment]
I tried v1.4.2. I’ve had error in sylius 1.1.6.

Enviado desde mi iPhone

**Comment by bitbager** [comment]
Seems like the Sitemap plugin in your instance has not been added during upgrading to 2.0.0/1.4.2. Initially, this feature was added in 2.0. Read the updating guide to see what's missing.

**Comment by damonsson** [comment]
Typically this bug will be caused if you haven't added to `config/bundles.php` line `SitemapPlugin\SitemapPlugin::class => ['all' => true]`
