### ISSUE TITLE
Make CMS RESTful

### ISSUE THREAD

**Issue by bitbager** [BitBagCommerce/SyliusCmsPlugin#20]
This plugin should also support the REST API and I think that it could be implemented with at least CQS pattern, maybe like the https://github.com/Sylius/SyliusShopApiPlugin does.

**Comment by pierre-H** [comment]
any news about that ?

**Comment by illestomas** [comment]
would like to use CMS for a SPA, any news ?
@bitbager ??

**Comment by bitbager** [comment]
Not yet. You can easily create your own API endpoints to fetch the proper CMS content if you need it for your SPA.

**Comment by pitosik** [comment]
Hello, in my opinion issue has a correct solution - closing.
