### ISSUE TITLE
problem with uploading images still remains

### ISSUE THREAD

**Issue by petrhamak** [BitBagCommerce/SyliusCmsPlugin#202]
Hello,

problem with uploading images still remains. After upload it returns url with double slashes. 

Easy fix it should be in UploadEditorImageAction.php:

replace
'url' => '/' . $media->getPath(),
to
'url' => $media->getPath(),

because $media->getPath() returns absolute path.

Petr

**Comment by bitbager** [comment]
It seems to be fixed: https://github.com/BitBagCommerce/SyliusCmsPlugin/blob/master/src/Controller/Action/Admin/UploadEditorImageAction.php#L61. Please reopen if needed.
