### ISSUE TITLE
Update/sync packagist with github

### ISSUE THREAD

**Issue by wadjeroudi** [BitBagCommerce/SyliusCmsPlugin#205]
Packagist dev-master is not in sync with github master.

https://packagist.org/packages/bitbag/cms-plugin#dev-master

**Comment by bitbager** [comment]
It's still not fixed. We just manually updated the plugin on packagist. We'd need to take care of it finally. CC @damonsson, @patrick477 😄

**Comment by tczaplicki** [comment]
this issue is outdated - the problem does not exist in the current version
