### ISSUE TITLE
Page in sitemap and not active fr the current channel

### ISSUE THREAD

**Issue by hmonglee** [BitBagCommerce/SyliusCmsPlugin#206]
When I add a page and don't enable it in the current channel, the page is visible in the sitemap. It must not appear in the sitemap.

**Comment by bitbager** [comment]
@stefandoorn, have you maybe any idea why this might happen?

**Comment by stefandoorn** [comment]
Probably because the usage of this method: https://github.com/BitBagCommerce/SyliusCmsPlugin/blob/master/src/SitemapProvider/PageUrlProvider.php#L91. What's the best way of finding pages enabled for a channel?

**Comment by pitosik** [comment]
I consider this topic to be outdated - closing.
