### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Prometee** [BitBagCommerce/SyliusCmsPlugin#210]
Hi I would like to use your plugin with sf 4.1.7 and Sylius 1.3.2, but the installation fail while doing :
```
composer req  bitbag/cms-plugin
```

```
Using version ^2.1 for bitbag/cms-plugin
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "^3.4|^4.1"
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for phpunit/phpunit (locked at 6.5.13, required as ^6.5) -> satisfiable by phpunit/phpunit[6.5.13].
    - bitbag/cms-plugin v2.1.0 requires matthiasnoback/symfony-config-test ^4.0 -> satisfiable by matthiasnoback/symfony-config-test[4.0.0].
    - bitbag/cms-plugin v2.1.1 requires matthiasnoback/symfony-config-test ^4.0 -> satisfiable by matthiasnoback/symfony-config-test[4.0.0].
    - Conclusion: don't install matthiasnoback/symfony-config-test 4.0.0
    - Installation request for bitbag/cms-plugin ^2.1 -> satisfiable by bitbag/cms-plugin[v2.1.0, v2.1.1].


Installation failed, reverting ./composer.json to its original content.
```

**Comment by bitbager** [comment]
Hi! What Sylius version are you working on?

**Comment by chaenu** [comment]
Same happened on a fresh installation of sylius 1.3.3. @Prometee I could install v2.0.5 without any problems, if this is an option for you.

**Comment by XaBe20** [comment]
The same with 1.3.3 

> Problem 1
>    - bitbag/cms-plugin v2.1.1 requires matthiasnoback/symfony-config-test ^4.0 -> satisfiable by matthiasnoback/symfony-config-test[4.0.0, 4.0.x-dev] but these conflict with your requirements or minimum-stability.
>    - bitbag/cms-plugin v2.1.0 requires matthiasnoback/symfony-config-test ^4.0 -> satisfiable by matthiasnoback/symfony-config-test[4.0.0, 4.0.x-dev] but these conflict with your requirements or minimum-stability.
>    - Installation request for bitbag/cms-plugin ^2.1 -> satisfiable by bitbag/cms-plugin[v2.1.0, v2.1.1].

**Comment by KirbyFox** [comment]
Just experienced exactly the same issue with Sylius 1.3.4

Looks like I'll have to find an alternative solution.

**Comment by bitbager** [comment]
We are going to resolve it soon. We will appreciate a pull request.

**Comment by Prometee** [comment]
The problem wasn't phpunit version but only the fact that `matthiasnoback/symfony-config-test` package wasn't in require-dev. This is the second time I made a pull request for this kind of error in Sylius, maybe Sylius should have a require-dev bundle to regroup dev dependencies over plugins and simplify futur update (because we have to manually diff sylius/sylius-standard composer.json at every update).
Also, a way of testing the app only in production mode in travis would be better.

**Comment by KirbyFox** [comment]
Sorry, just tried again and it still fails, using latest version of Sylius.

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - matthiasnoback/symfony-dependency-injection-test v3.0.0 conflicts with phpunit/phpunit[6.5.13].
    - matthiasnoback/symfony-dependency-injection-test v3.0.0 conflicts with phpunit/phpunit[6.5.13].
    - matthiasnoback/symfony-dependency-injection-test v3.0.0 conflicts with phpunit/phpunit[6.5.13].
    - Installation request for matthiasnoback/symfony-dependency-injection-test ^3.0 -> satisfiable by matthiasnoback/symfony-dependency-injection-test[v3.0.0].
    - Installation request for phpunit/phpunit (locked at 6.5.13, required as ^6.5) -> satisfiable by phpunit/phpunit[6.5.13].


Installation failed, reverting ./composer.json to its original content.

**Comment by Prometee** [comment]
@KirbyFox Do you use `dev-master` ?

**Comment by KirbyFox** [comment]
@Prometee Yes, and it still fails.

**Comment by Prometee** [comment]
@KirbyFox I just re-update my own `composer.json` to not use my fork anymore and update the `phpunit` version. and it works

**Comment by KirbyFox** [comment]
@Prometee I now get the following:

 Problem 1
    - The requested package phpunit/phpunit (locked at 6.5.13, required as ^7.0) is satisfiable by phpunit/phpunit[6.5.13] but these conflict with your requirements or minimum-stability.
  Problem 2
    - phpunit/phpunit 7.4.2 requires sebastian/environment ^4.0 -> satisfiable by sebastian/environment[4.0.x-dev] but these conflict with your requirements or minimum-stability.
    - Conclusion: don't install phpunit/phpunit 7.4.4
    - Conclusion: don't install phpunit/phpunit 7.4.3
    - Conclusion: don't install phpunit/phpunit 7.4.1
    - Conclusion: don't install phpunit/phpunit 7.4.0
    - Conclusion: don't install phpunit/phpunit 7.3.5
    - Conclusion: don't install phpunit/phpunit 7.3.4
    - Conclusion: don't install phpunit/phpunit 7.3.3
    - Conclusion: don't install phpunit/phpunit 7.3.2
    - Conclusion: don't install phpunit/phpunit 7.3.1
    - Conclusion: don't install phpunit/phpunit 7.3.0
    - Conclusion: don't install phpunit/phpunit 7.2.7
    - Conclusion: don't install phpunit/phpunit 7.2.6
    - Conclusion: don't install phpunit/phpunit 7.2.5
    - Conclusion: don't install phpunit/phpunit 7.2.4
    - Conclusion: don't install phpunit/phpunit 7.2.3
    - Conclusion: don't install phpunit/phpunit 7.2.2
    - Installation request for phpunit/phpunit-mock-objects (locked at 5.0.10) -> satisfiable by phpunit/phpunit-mock-objects[5.0.10].
    - Conclusion: don't install phpunit/phpunit 7.2.1
    - Installation request for phpunit/php-timer (locked at 1.0.9) -> satisfiable by phpunit/php-timer[1.0.9].
    - Conclusion: don't install phpunit/phpunit 7.2.0
    - phpunit/phpunit 7.0.0 requires phpunit/php-timer ^2.0 -> satisfiable by phpunit/php-timer[2.0.0].
    - phpunit/phpunit 7.0.1 requires phpunit/php-timer ^2.0 -> satisfiable by phpunit/php-timer[2.0.0].
    - phpunit/phpunit 7.0.2 requires phpunit/php-timer ^2.0 -> satisfiable by phpunit/php-timer[2.0.0].
    - phpunit/phpunit 7.0.3 requires phpunit/php-timer ^2.0 -> satisfiable by phpunit/php-timer[2.0.0].
    - phpunit/phpunit 7.1.0 requires phpunit/php-timer ^2.0 -> satisfiable by phpunit/php-timer[2.0.0].
    - phpunit/phpunit 7.1.1 requires phpunit/php-timer ^2.0 -> satisfiable by phpunit/php-timer[2.0.0].
    - phpunit/phpunit 7.1.2 requires phpunit/php-timer ^2.0 -> satisfiable by phpunit/php-timer[2.0.0].
    - phpunit/phpunit 7.1.3 requires phpunit/php-timer ^2.0 -> satisfiable by phpunit/php-timer[2.0.0].
    - phpunit/phpunit 7.1.4 requires phpunit/php-timer ^2.0 -> satisfiable by phpunit/php-timer[2.0.0].
    - phpunit/phpunit 7.1.5 requires phpunit/php-timer ^2.0 -> satisfiable by phpunit/php-timer[2.0.0].
    - Conclusion: don't install phpunit/php-timer 2.0.0
    - Installation request for phpunit/phpunit ^7.0 -> satisfiable by phpunit/phpunit[7.0.0, 7.0.1, 7.0.2, 7.0.3, 7.1.0, 7.1.1, 7.1.2, 7.1.3, 7.1.4, 7.1.5, 7.2.0, 7.2.1, 7.2.2, 7.2.3, 7.2.4, 7.2.5, 7.2.6, 7.2.7, 7.3.0, 7.3.1, 7.3.2, 7.3.3, 7.3.4, 7.3.5, 7.4.0, 7.4.1, 7.4.2, 7.4.3, 7.4.4].

**Comment by Prometee** [comment]
Do you merge your composer.json with tke latest one in Sylius/Sylius-standard ?

This is mine :
```
{
    "keywords": ["symfony", "symfony2", "sylius", "distribution", "ecommerce", "cart", "shopping"],
    "type": "project",
    "license": "proprietary",
    "homepage": "https://sylius.com",
    "authors": [
        {
            "name": "Paweł Jędrzejewski"
        },
        {
            "name": "Sylius project"
        },
        {
            "name": "Community contributions"
        }
    ],,
    "require": {
        "php": "^7.2",
        "bitbag/cms-plugin": "dev-master",
        "ekyna/payum-monetico": "dev-master",
        "flux/*******": "dev-master",
        "flux/*******": "dev-master",
        "flux/*******": "dev-master",
        "flux/*******": "dev-master",
        "flux/*******": "dev-master",
        "php-http/httplug-bundle": "^1.11",
        "prometee/sylius-payum-monetico-plugin": "dev-master",
        "sensiolabs/security-checker": "^5.0",
        "stefandoorn/sitemap-plugin": "^1.0",
        "stefandoorn/sylius-google-tag-manager-enhanced-ecommerce-plugin": "^0.6.1",
        "sylius/invoicing-plugin": "^0.5.1",
        "sylius/refund-plugin": "^0.4.3",
        "sylius/sylius": "1.3.*@dev",
        "symfony/flex": "^1.1"
    },
    "require-dev": {
        "behat/behat": "^3.4",
        "behat/mink": "^1.7@dev",
        "behat/mink-browserkit-driver": "^1.3",
        "behat/mink-extension": "^2.2",
        "behat/mink-selenium2-driver": "^1.3",
        "friends-of-behat/context-service-extension": "^1.2",
        "friends-of-behat/cross-container-extension": "^1.1",
        "friends-of-behat/page-object-extension": "^0.2",
        "friends-of-behat/service-container-extension": "^1.0",
        "friends-of-behat/suite-settings-extension": "^1.0",
        "friends-of-behat/symfony-extension": "^1.2.1",
        "friends-of-behat/variadic-extension": "^1.1",
        "lchrusciel/api-test-case": "^3.0",
        "lakion/mink-debug-extension": "^1.2.3",
        "phpspec/phpspec": "^5.0",
        "phpunit/phpunit": "^7.0",
        "stripe/stripe-php": "^4.1",
        "sylius-labs/coding-standard": "^2.0",
        "symfony/browser-kit": "^3.4|^4.1",
        "symfony/debug-bundle": "^3.4|^4.1",
        "symfony/dotenv": "^3.4|^4.1",
        "symfony/intl": "^3.4|^4.1",
        "symfony/web-profiler-bundle": "^3.4|^4.1",
        "symfony/web-server-bundle": "^3.4|^4.1"
    },
    "prefer-stable": true,
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install --symlink --relative %PUBLIC_DIR%": "symfony-cmd",
            "security-checker security:check": "script"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "config": {
        "platform": {
            "php": "7.2"
        },
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true
    },
    "extra": {
        "symfony": {
            "allow-contrib": "true"
        },
        "branch-alias": {
            "dev-master": "1.3-dev"
        }
    }
}

```

**Comment by KirbyFox** [comment]
@Prometee I just ran Composer Update and it all seems to have installed, but I have no new menu option within Admin.

**Comment by XaBe20** [comment]
With `composer require bitbag/cms-plugin:@dev`, the composer installation works.

But when I configure the bundle, I have a problem with sitemap-plugin :
> Exception thrown when handling an exception (Symfony\Component\Config\Exception\FileLoaderLoadException: Do not add the "extra" loader twice in . (which is being imported from "Sylius/vendor/stefandoorn/sitemap-plugin/src/Resources/config/routing.yml"). Make sure there is a loader supporting the "sitemap" type.)

**Comment by Prometee** [comment]
I have this error two because the routing from this bundle import the default routing of `stefandoorn /sitemap-plugin`. I configure it like this :
```
# config/routes/bitbag_cms.yaml

bitbag_sylius_cms_plugin_admin:
    resource: "@BitBagSyliusCmsPlugin/Resources/config/routing/admin.yml"
    prefix: /admin

bitbag_sylius_cms_plugin_shop:
    resource: "@BitBagSyliusCmsPlugin/Resources/config/routing/shop.yml"
    prefix: /{_locale}
    requirements:
        _locale: ^[a-z]{2}(?:_[A-Z]{2})?$
```

**Comment by KirbyFox** [comment]
When I run bin/console doctrine:migrations:migrate

It fails with the following error:

SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'sylius_adjustment' already exists

**Comment by ersinpw** [comment]
The error is still present, tried with a fresh install:

```
$ composer require bitbag/cms-plugin
Using version ^2.1 for bitbag/cms-plugin
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "^3.4|^4.1"
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for phpunit/phpunit (locked at 6.5.13, required as ^6.5) -> satisfiable by phpunit/phpunit[6.5.13].
    - bitbag/cms-plugin v2.1.0 requires matthiasnoback/symfony-config-test ^4.0 -> satisfiable by matthiasnoback/symfony-config-test[4.0.0].
    - bitbag/cms-plugin v2.1.1 requires matthiasnoback/symfony-config-test ^4.0 -> satisfiable by matthiasnoback/symfony-config-test[4.0.0].
    - Conclusion: don't install matthiasnoback/symfony-config-test 4.0.0
    - Installation request for bitbag/cms-plugin ^2.1 -> satisfiable by bitbag/cms-plugin[v2.1.0, v2.1.1].
```

**Comment by Prometee** [comment]
@ersinpw : please read all this thread : [answer is here](https://github.com/BitBagCommerce/SyliusCmsPlugin/issues/210#issuecomment-441281273)

**Comment by diimpp** [comment]
Why it's closed? Clearly still a issue. Sylius-standard:1.3, not installable by plugin's release or dev-master. Various issues with change to `phpunit/phpunit:^7.0`.

**Comment by stefandoorn** [comment]
Can't we allow `matthiasnoback/symfony-config-test` in 2 versions and PHPUnit in 6.5 + 7.0? There's some rather overlap in there, just some PHPUnit version stuff. That's what I do e.g. here: https://github.com/stefandoorn/sitemap-plugin/blob/master/composer.json. Makes the plugin more useable, now I need to upgrade my whole project to PHPUnit 7 first before being able to update. Quite an hassle.

**Comment by bitbager** [comment]
Sorry, I must have closed this by an accident. Can I count on you guys regarding fixing this bug?

**Comment by Prometee** [comment]
@bitbager done. I also fix some other deps.

**Comment by bitbager** [comment]
Hello guys!

Sorry for a late response, I've been kind of busy recently. Thank you for your PR, I am going to merge it in a minute!

**Comment by jcgdjob** [comment]
Still can't install by composer...

**Comment by Prometee** [comment]
`dev-master` ?

**Comment by jcgdjob** [comment]
> `dev-master` ?

Yes, tried: 
`composer require bitbag/cms-plugin dev-master`
and
update composer json to:
`"bitbag/cms-plugin": "dev-master",`
and `composer update bitbag/cms-plugin`

**Comment by Prometee** [comment]
I'm doing the same, what is you error ? Do you also update you composer.json according to Sylius/Sylius-standard ?

**Comment by jcgdjob** [comment]
I have installed the latest version of Sylius (1.3.5). Do I still need to update sth on composer.json on Sylius?

**Comment by Prometee** [comment]
What is you error , maybe it's a new one because I have the same installation and it works.

**Comment by jcgdjob** [comment]
Same error, seems:

```
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - matthiasnoback/symfony-config-test 4.0.0 conflicts with phpunit/phpunit[6.5.13].
    - matthiasnoback/symfony-config-test 4.0.0 conflicts with phpunit/phpunit[6.5.13].
    - matthiasnoback/symfony-config-test 4.0.0 conflicts with phpunit/phpunit[6.5.13].
    - bitbag/cms-plugin dev-master requires matthiasnoback/symfony-config-test ^4.0 -> satisfiable by matthiasnoback/sym
fony-config-test[4.0.0].
    - Installation request for bitbag/cms-plugin dev-master -> satisfiable by bitbag/cms-plugin[dev-master].
    - Installation request for phpunit/phpunit (locked at 6.5.13, required as ^6.5) -> satisfiable by phpunit/phpunit[6.
5.13].
```

**Comment by Prometee** [comment]
Composer is not retrieving the latest version of this repository, because it say that it require matthiasnoback/symfony-config-test ^4.0 and the current composer is require ^3.0 (https://github.com/BitBagCommerce/SyliusCmsPlugin/blob/e3a5bf7ced09de4eaf8425959134329649eaeabc/composer.json#L33)

**Comment by stefandoorn** [comment]
Packagist maybe not up to date?

**Comment by stefandoorn** [comment]
#205

**Comment by Prometee** [comment]
@stefandoorn yes you are right
@bitbager manually update the packagist repository ?

**Comment by Prometee** [comment]
@jcgdjob add this to your `composer.json` :
```
"repositories": [
        {
            "type": "github",
            "url": "https://github.com/BitBagCommerce/SyliusCmsPlugin"
        }
    ],
```

That's why it works for me.

**Comment by jcgdjob** [comment]
> "repositories": [ { "type": "github", "url": "https://github.com/BitBagCommerce/SyliusCmsPlugin" } ],

It works, thanks!

**Comment by Bonobomagno** [comment]
so still not updated?

**Comment by stefandoorn** [comment]
I think this might solve it: https://github.com/stefandoorn/sitemap-plugin/pull/123
