### ISSUE TITLE
Fixture for multiple channels

### ISSUE THREAD

**Issue by Prometee** [BitBagCommerce/SyliusCmsPlugin#218]
Fixture load use `ChannelContextInterface` witch is not able to retrieve any context in command line env because there is no request to get and guess the current `Channel`.

So `Channel` has to become a part of the fixture definition.

**Comment by Prometee** [comment]
Never mind I was using `ormpurger` filter so my channel has been removed, but we have to keep a way to put fixture contents into other channels.

**Comment by bitbager** [comment]
The fixtures are just a basic implementation for MVP usage. If you need anything more, please either provide a PR or use custom Sylius fixtures instead.
