### ISSUE TITLE
bitbag_sylius_cms_plugin_shop_block_render requires 2 queries

### ISSUE THREAD

**Issue by stefandoorn** [BitBagCommerce/SyliusCmsPlugin#223]
Looking into some performance optimisations, and one of the issues is that for each of my blocks rendered, a second query is done to fetch the image information (and/or translation). It seems to me that that's not really necessary. In my case I started digging into this as I don't need the image there, but that might be different for others. 

I'm trying to figure out a method to get rid of these 2 queries, and move them into one. The repository method involved is `BlockRepository::findOneEnabledByCode`.

Queries on this URL: `http://sylius.local/app_dev.php/nl_NL/block/block_code_here` (next to the default Sylius ones):

```
SELECT b0_.id AS id_0, b0_.code AS code_1, b0_.type AS type_2, b0_.enabled AS enabled_3 FROM bitbag_cms_block b0_ WHERE b0_.code = ? AND b0_.enabled = 1
Parameters:
[▼
  "block_code_here"
]
```

```
SELECT t0.id AS id_1, t0.name AS name_2, t0.content AS content_3, t0.link AS link_4, t0.locale AS locale_5, t6.type AS type_7, t6.path AS path_8, t6.id AS id_9, t6.owner_id AS owner_id_10, t0.translatable_id AS translatable_id_11 FROM bitbag_cms_block_translation t0 LEFT JOIN bitbag_cms_block_image t6 ON t6.owner_id = t0.id WHERE t0.translatable_id = ? AND t0.locale = ? LIMIT 1

Parameters:[▼   1   "nl_NL" ]
```

Any suggestions here? Willing to PR if I find the improvement :-)

**Comment by stefandoorn** [comment]
Adjusting the repository method in (just for testing an hardcoded locale):

```
    public function findOneEnabledByCode(string $code): ?BlockInterface
    {
        return $this->createQueryBuilder('o')
            ->addSelect('translation')
            ->innerJoin('o.translations', 'translation', 'WITH', 'translation.locale = :locale')
            ->leftJoin('translation.image', 'image')
            ->andWhere('o.code = :code')
            ->andWhere('o.enabled = true')
            ->setParameter('locale', 'nl_NL')
            ->setParameter('code', $code)
            ->getQuery()
            ->getOneOrNullResult()
        ;
    }
```

Changes the queries, but doesn't take the image one away:

```
SELECT b0_.id AS id_0, b0_.code AS code_1, b0_.type AS type_2, b0_.enabled AS enabled_3, b1_.id AS id_4, b1_.name AS name_5, b1_.content AS content_6, b1_.link AS link_7, b1_.locale AS locale_8, b1_.translatable_id AS translatable_id_9 FROM bitbag_cms_block b0_ INNER JOIN bitbag_cms_block_translation b1_ ON b0_.id = b1_.translatable_id AND (b1_.locale = ?) LEFT JOIN bitbag_cms_block_image b2_ ON b1_.id = b2_.owner_id WHERE b0_.code = ? AND b0_.enabled = 1
Parameters:
[▼
  "nl_NL"
  "block_code_here"
]
```

```
SELECT t0.type AS type_1, t0.path AS path_2, t0.id AS id_3, t0.owner_id AS owner_id_4 FROM bitbag_cms_block_image t0 WHERE t0.owner_id = ?
Parameters:
[▼
  1
]
```

IMO the first query returns all the required information at once here, but it doesn't seem to be taken into consideration for the second query. Might be something to do with the fact that for the image an `oneToOne` relation is used.

**Comment by stefandoorn** [comment]
Using v1.4.3 of the plugin btw.

**Comment by bitbager** [comment]
Hello Stefan! 

Thank you for your effort. @damonsson, kind of makes sense for me. Can I ask you to take a look at it?

**Comment by pitosik** [comment]
I consider this topic to be outdated - closing.
