### ISSUE TITLE
Cannot use template with bitbag_sylius_cms_plugin_shop_media_render

### ISSUE THREAD

**Issue by pierre-H** [BitBagCommerce/SyliusCmsPlugin#224]
Thank you for your great work

The use of Template option seems to be ignored when I want to render **bitbag_sylius_cms_plugin_shop_media_render**.

Maybe this is related to #149 ...

I use the dev-master version with Sylius, 1.3.5

**Comment by bitbager** [comment]
Hello Pierre, 

Currently `BitBag\SyliusCmsPlugin\Twig\Extension\RenderMediaExtension` does not support a template parameter. We would appreciate a PR with this, but you can also override these templates and it should do the trick: https://github.com/BitBagCommerce/SyliusCmsPlugin/tree/master/src/Resources/views/Media

**Comment by JoppeDC** [comment]
I just ran into the same issue. The docs seem to state that its possible to use a custom template.

`{{ render(path('bitbag_sylius_cms_plugin_shop_media_render', {'code' : 'file', 'template' : '@App/Some/Template/_path.html.twig'})) }}`

**Comment by tczaplicki** [comment]
this issue is outdated - the problem was resolved in #295
