### ISSUE TITLE
Edit page: Product autocomplete causes error

### ISSUE THREAD

**Issue by matthiez** [BitBagCommerce/SyliusCmsPlugin#242]
Hi,

I stumble upon this error when searching for products in the Admin.Pages grid.

"message": "Too few arguments to function Doctrine\\ORM\\EntityRepository::__construct(), 0 passed in /sylius/var/cache/dev/ContainerIcERujV/getBitbagSyliusCmsPlugin_Controller_Action_Admin_ProductSearchService.php on line 15 and exactly 2 expected"

Any ideas? Thanks!

**Comment by nicoplh** [comment]
Same here, any news ?

**Comment by bitbager** [comment]
Should be fixed on master and in the upcoming release
