### ISSUE TITLE
Block creation product autocomplete error

### ISSUE THREAD

**Issue by Simas06** [BitBagCommerce/SyliusCmsPlugin#251]
Error occurred while creating a block in backend and using product autocomplete field 

Autocomplete makes request to url: 

`http://127.0.0.1:8000/admin/ajax/products/search-by-name?phrase=boo&_=1553541976318 
`

which return error message:

`Too few arguments to function Doctrine\\ORM\\EntityRepository::__construct(), 0 passed in /.../var/cache/dev/ContainerWYlQ9es/getBitbagSyliusCmsPlugin_Controller_Action_Admin_ProductSearchService.php on line 15 and exactly 2 expected`

Error occurs with fresh sylius (1.4.1) framework and plugin installation. I used sylius sample data

**Comment by matthiez** [comment]
See also #242

**Comment by Simas06** [comment]
Any news? :confused:

**Comment by bitbager** [comment]
Fixed ✅
