### ISSUE TITLE
Error while deleting Media

### ISSUE THREAD

**Issue by Kriz83** [BitBagCommerce/SyliusCmsPlugin#252]
An error occurred while deleting a media in the backend when media has selected sections or products.
Error message example:

`An exception occurred while executing 'DELETE FROM bitbag_cms_media WHERE id = ?' with params [1]:
SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`sylius_dev`.`bitbag_cms_media_sections`, CONSTRAINT `FK_98BC300EA9FDD75` FOREIGN KEY (`media_id`) REFERENCES `bitbag_cms_media` (`id`))`

Error occurs in Sylius „1.1.*” and „1.4.*” versions.

**Comment by viikas** [comment]
Anyone fixed this?

**Comment by olia-bn** [comment]
This issue is also occurs when attempting to delete Blocks linked to sections or products.
