### ISSUE TITLE
CK Editor assets are deleted on page load (on the server)

### ISSUE THREAD

**Issue by castwayalldc** [BitBagCommerce/SyliusCmsPlugin#253]
Hi guys, I have issues on the server with CK Editor JS/CSS files since they are being deleted everytime I reload any page.

I'm my project the files are located under "public/bundles/_themes/sylius/bootstrap-theme/fosckeditor"

And it initlially looks like this: [https://imgur.com/2mtWXLo](url)
But after I try to work on the admin panel, as I do any action then the files are deleted and it says the file is not found, so after checking the same folder, most of the files are gone.
[https://imgur.com/XStQm2w](url)

I am using: 
"bitbag/cms-plugin": "^2.3"
"sylius/sylius": "~1.4"

Also please note this doesn't happen on my local environment (running vagrant with ubuntu16).

Can someone please help?
Thanks in advance.

**Comment by bitbager** [comment]
Have you installed the theme assets?

**Comment by castwayalldc** [comment]
Sorry I forgot to update this issue. Actually, I had to re-generate the assets by executing the commands on the server using ssh, because the symlinks were being automatically deleted if I just uploaded the whole public folder.
