### ISSUE TITLE
which version would be support all plugins

### ISSUE THREAD

**Issue by parthajudiya** [BitBagCommerce/SyliusCmsPlugin#254]
helloi would like to almost plugin inbuild installed i can downmload  full package including plugins or which version would be support all plugins and library i would like to test and learning purpose want to for social plugin and other for my internal learning for symfony so can u guide me how to do inbuild all plugin package i can or which version will support  plougins case plugisn are different different symfony version installation step so

**Comment by bitbager** [comment]
I am sorry, I don't get your question at all but I think you can ask it on the Sylius Slack channel. There is a huge community that can help you learning Sylius.
