### ISSUE TITLE
Upgrade to sylius/sylius:~1.5.0

### ISSUE THREAD

**Issue by chadyred** [BitBagCommerce/SyliusCmsPlugin#256]
Is it possible to migrate this plugin to `sylius/sylius:~1.5.0` dependency for this plugin and maybe others ? Thanks !!

**Comment by Prometee** [comment]
I send a very little PR just to check if tests are OK, maybe there is more to do but it's a first step...

**Comment by Prometee** [comment]
So far no warnings or errors on my `dev` env but there is many FCKEditor deprecation logs. So maybe someone could try to make a PR with an upgrade on FCKeditor to resolve those deprecations
