### ISSUE TITLE
Locked Sylius version

### ISSUE THREAD

**Issue by mikemix** [BitBagCommerce/SyliusCmsPlugin#258]
Why the latest releases are locked to newest Sylius ^1.4? Isn't this plugin compatible with previous Sylius versions? Like 1.2 or 1.3?

**Comment by oallain** [comment]
Hello,

i think it's because since 1.4 many thing change on tests, see https://github.com/Sylius/PluginSkeleton/blob/master/UPGRADE-1.4.md

Regards,
