### ISSUE TITLE
Can't override validation yaml page translation

### ISSUE THREAD

**Issue by rowanvanekeren** [BitBagCommerce/SyliusCmsPlugin#261]
Hey i'm having troubles with overriding validation in sylius 

i tried it in config/validator/validation.yml and config/packages/validator/validation.yml and even in config/packages/validator.yaml. I cant get it to work.

Any idea or an example how to override soms validation rules for form fields?

**Comment by patrick477** [comment]
You cannot overwrite validation, you can change validation groups and add a new validation file.
