### ISSUE TITLE
Add "releaseAt" field to page

### ISSUE THREAD

**Issue by vasilvestre** [BitBagCommerce/SyliusCmsPlugin#263]
I would like to add a releaseAt field to page in order to do not show them before a date.

Is it possible ? Not documented ?

Thanks

**Comment by bitbager** [comment]
We'd love to accept such PR as long as it meets our standards described on https://github.com/BitBagCommerce/BitBagBible. Feel free to open one 🙂

**Comment by leszczuu** [comment]
fixed with 3.0.0 release
