### ISSUE TITLE
Conflict with sylius/theme-bundle

### ISSUE THREAD

**Issue by olia-bn** [BitBagCommerce/SyliusCmsPlugin#270]
It seems to me that SyliusCmsPlugin conflicts with sylius/theme-bundle

Theme Bundle uses custom path resolve function in `Sylius\Bundle\ThemeBundle\Asset\PathResolver`:
```
    public function resolve(string $path, ThemeInterface $theme): string
    {
        return str_replace('bundles/', 'bundles/_themes/' . $theme->getName() . '/', $path);
    }
```

This results in invalid asset path in the admin for SyliusCmsPlugin assets (both JS and CSS) if a theme is set since the asset paths `bundles/bitbagsyliuscmsplugin/...` will result in `/bundles/_themes/[theme_name]/bitbagsyliuscmsplugin/...`

Workaround: create a symlink manually

**Comment by armellarcier** [comment]
This is should be reopened for a better solution

**Comment by stephane-lou** [comment]
No resolution for this ? Drives me crazy
