### ISSUE TITLE
Language switcher should redirect to correct language page

### ISSUE THREAD

**Issue by Zilus** [BitBagCommerce/SyliusCmsPlugin#271]
I don't know if this is in fact a bug or a improvement request.

When on a page created by the plugin, lets say `domain.com/pages/about` and then you switch language to "Spanish" (in the same url), you get redirected to `domain.com/pages/about` and of course that url is for the English page. It should redirect to: `domain.com/pages/spanish-about`.

**Comment by pitosik** [comment]
Hello, I consider this topic to be outdated - closing.

**Comment by SuperToma** [comment]
Hello :wave:
Why this topic is considered as outdated ? :see_no_evil:
