### ISSUE TITLE
stefandoorn / sitemap-plugin dependency version

### ISSUE THREAD

**Issue by afasciaux** [BitBagCommerce/SyliusCmsPlugin#287]
Hi,

I'd like to update stefandoorn/sitemap-plugin to version 2.0, mainly for cli sitemap generation, but i'm stuck with the 1.0 dependency requirements .

Any chance to have it one the new version ?

Thanks a lot !

**Comment by leszczuu** [comment]
Removed dependency on sitemap plugin, You can now require it optionaly, so You are able to specify version.

**Comment by leszczuu** [comment]
https://github.com/BitBagCommerce/SyliusCmsPlugin/pull/347
updated to 2.0 in new release, intention is to make it optional.
