### ISSUE TITLE
Link to cms page from code

### ISSUE THREAD

**Issue by Florian-Merle** [BitBagCommerce/SyliusCmsPlugin#301]
# Issue:
I had to generate a link to a CMS page from its code, but currently, there is no way to do that.

# Proposition:
Add a twig function that create a link from a code.

E.g.

```twig
{{ bitbag_cms_link_by_code('CODE') }}
```

Would generate the following link:
```html
<a href="/_locale/page/slug">Name when linked</a>
```

For customization, attributes could be added to the link just like the [`attr` option in Symfony FormType Field](https://symfony.com/doc/current/reference/forms/types/form.html#attr).

Also an option for a custom template could be used to generate the link.

I already did the development on my projet, let me know if you're interested in this feature, and I should invest some time in implementing it on the plugin.

**Comment by patrick477** [comment]
thanks for the suggestion, we will gladly accept PR with a new function :) I think a good idea would be to add a similar function as for routing generation https://symfony.com/doc/current/templates.html#linking-to-pages
