### ISSUE TITLE
Unknown "bitbag_cms_render_link_for_code" function

### ISSUE THREAD

**Issue by NasH5169** [BitBagCommerce/SyliusCmsPlugin#303]
Hello,

First thanks for the plugin. It is great.

On a fresh Sylius install (1.7.3), i've follow the plugin install guide. Easy.

I was able to add a page with the admin part --> OK.

I'm just trying to render a link with:

`{{ bitbag_cms_render_link_for_code('code') }}`

I got "Unknown "bitbag_cms_render_link_for_code" function"

Any idea?

Thanks.

**Comment by patrick477** [comment]
Hi, what version of plugin do you have?

**Comment by NasH5169** [comment]
"bitbag/cms-plugin": "^2.4"

Installed with: `composer require bitbag/cms-plugin`

https://github.com/BitBagCommerce/SyliusCmsPlugin/blob/master/doc/installation.md

**Comment by patrick477** [comment]
this twig function is not yet available in the stable version of the plugin, if you want to use this function download  `dev-master` version

**Comment by NasH5169** [comment]
It's working!

I've switched on the dev-master.

Thanks again.
