### ISSUE TITLE
Can't override BlockTranslation

### ISSUE THREAD

**Issue by next-sentence** [BitBagCommerce/SyliusCmsPlugin#307]
Can't override BlockTranslation because of this, should return BlockTranslationInterface

```
    protected function createTranslation(): BlockTranslation
    {
        return new BlockTranslation();
    }
```

**Comment by kptLucek** [comment]
@next-sentence does this issue still persists for you?

**Comment by leszczuu** [comment]
Should be fixed in newest version.
