### ISSUE TITLE
assets symlink dissapear after composer install

### ISSUE THREAD

**Issue by dakorpar** [BitBagCommerce/SyliusCmsPlugin#323]
this is in my composer.json
```
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    }
```

Everytime I run composer install I have to also run

php bin/console sylius:theme:assets:install --symlink

**Comment by leszczuu** [comment]
Closing as this is sylius issue, not CMS plugin issue. Scripts defined in plugin's composer.json should not affect project using plugin.
