### ISSUE TITLE
Problems trying to extend Page entity

### ISSUE THREAD

**Issue by porl** [BitBagCommerce/SyliusCmsPlugin#324]
I am trying to extend the CMS for a custom site and am trying to follow along with https://docs.sylius.com/en/latest/customization/model.html in order to create a custom extended Page.php (rather than editing the code in the bundle itself).

Unfortunately when I get to the end of step 2 I get errors with every console command as follows:

`Class "App\Entity\CMS\Page" sub class of "BitBag\SyliusCmsPlugin\Entity\Page" is not a valid entity or mapped super class.`

For reference, here is my preliminary version of the extended page (just one field for now as I am testing the process):

```php
<?php

declare(strict_types=1);

/**
 * @ORM\Entity()
 * @ORM\Table(name="bitbag_cms_page")
 */
namespace App\Entity\CMS;

use Doctrine\ORM\Mapping as ORM;

use BitBag\SyliusCmsPlugin\Entity\Page as BasePage;
use BitBag\SyliusCmsPlugin\Entity\PageInterface;

class Page extends BasePage implements PageInterface
{

    /** @ORM\Column(type="boolean", nullable=true) */
    private $showContactForm;

    public function getShowContactForm(): ?bool
    {
        return $this->showContactForm;
    }

    public function setShowContactForm(bool $showContactForm): void
    {
        $this->showContactForm = $showContactForm;
    }
}
```

I assume I am doing something stupid but is there some info that can help me do this the correct way?

Thanks!

**Comment by kptLucek** [comment]
Hi there, and thanks for getting intouch!

First of all, check your mapping, it's location to be more precise :)
Second, you need to tweak resource configuration for `bitbag_sylius_cms_plugin.page` - [check this location](https://github.com/BitBagCommerce/SyliusCmsPlugin/blob/master/src/Resources/config/resources/page.yml)

Based on how it's designed, you should (propably) create new file under your **config/packages/** with something similar to this:
```yaml
sylius_resource:
    resources:
        bitbag_sylius_cms_plugin.page:
            classes:
                model: App\Entity\CMS\Page
```

**Comment by porl** [comment]
Thanks for the quick response! I forgot to mention I have already done that sorry. Doing `php bin/console debug:container --parameter=bitbag_sylius_cms_plugin.model.page.class` gives the correct reference, so I know the config is being loaded correctly, however I still get the error on every command (including this one).

Not sure if it helps, but the error appears twice each time:

```
porl@porl-legion ~/w/s/sylius-standard (master)> php bin/console debug:container --parameter=bitbag_sylius_cms_plugin.model.page.class

                                                                                                                        
 [WARNING] Some commands could not be registered:                                                                       
                                                                                                                        

In MappingException.php line 340:
                                                                                                                              
  Class "App\Entity\CMS\Page" sub class of "BitBag\SyliusCmsPlugin\Entity\Page" is not a valid entity or mapped super class.  
                                                                                                                              

In MappingException.php line 340:
                                                                                                                              
  Class "App\Entity\CMS\Page" sub class of "BitBag\SyliusCmsPlugin\Entity\Page" is not a valid entity or mapped super class.  
                                                                                                                              


                                                                                                                        
 [WARNING] Some commands could not be registered:                                                                       
                                                                                                                        

In MappingException.php line 340:
                                                                                                                              
  Class "App\Entity\CMS\Page" sub class of "BitBag\SyliusCmsPlugin\Entity\Page" is not a valid entity or mapped super class.  
                                                                                                                              

In MappingException.php line 340:
                                                                                                                              
  Class "App\Entity\CMS\Page" sub class of "BitBag\SyliusCmsPlugin\Entity\Page" is not a valid entity or mapped super class.  
                                                                                                                              

 ------------------------------------------- --------------------- 
  Parameter                                   Value                
 ------------------------------------------- --------------------- 
  bitbag_sylius_cms_plugin.model.page.class   App\Entity\CMS\Page  
 ------------------------------------------- --------------------- 

porl@porl-legion ~/w/s/sylius-standard (master)> 
```

**Comment by kptLucek** [comment]
By "check your mapping" i've meant:

```php
/**
 * @ORM\Entity()
 * @ORM\Table(name="bitbag_cms_page")
 */
namespace App\Entity\CMS;
``` 
:)

**Comment by porl** [comment]
Sorry I mixed the two points together. What should that be changed to? I am not quite sure how to apply the info from the link I pasted to this class. Sorry if it is a stupid question, the last time I worked in Symfony version 2 was new! haha

**Comment by kptLucek** [comment]
No problem :)

First of all, move your ORM mapping over your class (currently it's over it's namespace), so doctrine's annotation reader will parse this as an valid entity.

Everything should work like charm after that change.

**Comment by porl** [comment]
Thank you! I knew I'd done something stupid ;)

**Comment by porl** [comment]
Sorry, one further question - how would I go about adding this field to the crud forms? I found the form being built here `vendor/bitbag/cms-plugin/src/Form/Type/Translation/PageTranslationType.php` so would I just override this class in the same manner as the other? What would I need to put in the yaml file to point to this class?
Thank you

**Comment by porl** [comment]
Actually the field that I want to override now is not in the translatable section so I'm assuming I'd do the above override to `vendor/bitbag/cms-plugin/src/Form/Type/PageType.php`. I found the format for the yaml file and it now reads as follows:

```yaml
sylius_resource:
    resources:
        bitbag_sylius_cms_plugin.page:
            classes:
                model: App\Entity\CMS\Page
                form: App\Form\Type\CMS\PageType
```

Unfortunately this class is a "final" type, and so I can't extend it like I did the Page entity one. So I have tried to copy it as-is (changing the namespace of course) but now get an error

```
Too few arguments to function Sylius\Bundle\ResourceBundle\Form\Type\AbstractResourceType::__construct(), 0 passed in /home/porl/workspace/symfony/sylius-standard/var/cache/dev/ContainerFWGEfEJ/getPageTypeService.php on line 14 and at least 1 expected
```

**Comment by porl** [comment]
I assume this is some sort of dependency injection issue or similar. Is there any way I can do this without modifying your core code to allow extending the PageType class?

**Comment by kptLucek** [comment]
@porl [Check this](https://symfony.com/doc/current/form/create_form_type_extension.html) + eventually an template override.

**Comment by porl** [comment]
Thank you!

**Comment by porl** [comment]
Thank you! All working now.
