### ISSUE TITLE
Including more than one twig function in WYSIWYG block  / page fails due to wrong regex

### ISSUE THREAD

**Issue by HVStechnik** [BitBagCommerce/SyliusCmsPlugin#325]
**Issue**
Editors of blocks, pages, and media can use twig functions in the admin panel (see https://github.com/BitBagCommerce/SyliusCmsPlugin/blob/master/doc/twig-functions-in-admin.md). However, this works only if there is just one twig function within each textarea. If the user places more than one twig function on one page / in one block, the function is not replaced. 

**Reason**
The regex in SyliusCmsPlugin/src/Twig/Parser/ContentParser.php line 35 (```{{\s*(?P<method>.+)\s*\((?P<arguments>.*)\)\s*}}```) matches all content from the first ```{{``` to the last ```}}```on the page / in the block. If there are two functions, everything inbetween is matched by the regex. Consequently, both functions are not recognized.

**Proposed solution**
The regex in SyliusCmsPlugin/src/Twig/Parser/ContentParser.php line 35 (```{{\s*(?P<method>.+)\s*\((?P<arguments>.*)\)\s*}}```) should be replaced by ```{{\s*(?P<method>[^\(]+)\s*\((?P<arguments>[^\)]*)\)\s*}}```

**Comment by leszczuu** [comment]
fixed with 3.0.0 release
