### ISSUE TITLE
CK editor is not working on pages content

### ISSUE THREAD

**Issue by kannanseeni** [BitBagCommerce/SyliusCmsPlugin#326]
Suddenly CK editor is not working on pages content

**Comment by leszczuu** [comment]
Did You follow https://symfony.com/doc/master/bundles/FOSCKEditorBundle/usage/ckeditor.html installtion instructions? Does it work in block content for You? 
Does chrome console display any information, for example 'CKEditor plugin could not be loaded' ?

**Comment by leszczuu** [comment]
I am closing this issue for now, please provide more info if it is still not working for You.
