### ISSUE TITLE
Sections search bad response

### ISSUE THREAD

**Issue by hdumazeau** [BitBagCommerce/SyliusCmsPlugin#328]
Hello, 
V2.4.0
Page: /media/new

The section return list is invalid. The message undefined is displayed.

You will find the answer json of the api as well as the forehead.
![Screenshot_20201127_211218](https://user-images.githubusercontent.com/25611626/100481821-b82cda00-30f5-11eb-9464-9daa9a9d1265.png)
![Screenshot_20201127_211238](https://user-images.githubusercontent.com/25611626/100481824-b9f69d80-30f5-11eb-93a5-392f495ce0dc.png)

**Comment by leszczuu** [comment]
fixed with 3.0.0 release
