### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by bondie** [BitBagCommerce/SyliusCmsPlugin#340]
Hi guys, is posibble to publish new release? We would like to use this new feature - https://github.com/BitBagCommerce/SyliusCmsPlugin/commit/27acd7271ccd4ad9e76543694133454bcf28344a

We are using composer validate command in pipelines, so we can't require dev-master branch in composer.json.

Thanks!

**Comment by leszczuu** [comment]
fixed with 3.0.0 release
