### ISSUE TITLE
Integration with Sylius 1.9

### ISSUE THREAD

**Issue by Tomanhez** [BitBagCommerce/SyliusCmsPlugin#342]
After few last changes on Sylius master(1.9) SyliusCmsPlugin is incompatible:
 - Replace any usages of `Symfony\Bundle\FrameworkBundle\Templating\EngineInterface` with `Twig\Environment`
 - Inject `twig` service into your services instead of `templating`
 - `src/Controller/BlockController.php` use `setTemplate` method from `FOS\RestBundle\View\View` that is not available with last version using in Sylius

**Comment by jbcr** [comment]
The `stefandoorn/sitemap-plugin` version 1.0.x is not compatible with Symfony 5.x too

**Comment by jbcr** [comment]
https://github.com/BitBagCommerce/SyliusCmsPlugin/pull/317

**Comment by leszczuu** [comment]
fixed with 3.0.0 release
