### ISSUE TITLE
Incompatible with sylius 1.9

### ISSUE THREAD

**Issue by corneagigi** [BitBagCommerce/SyliusCmsPlugin#348]
When do you plan to make it compatible with sylius 1.9 ?
Thanks

**Comment by leszczuu** [comment]
It will be compatible with 1.9 after after version 3.0 of the plugin is released 
https://github.com/BitBagCommerce/SyliusCmsPlugin/pull/347

**Comment by leszczuu** [comment]
fixed with 3.0.0 version release
