### ISSUE TITLE
Consider allowing Sylius 1.8.* for 3.*

### ISSUE THREAD

**Issue by xchopin** [BitBagCommerce/SyliusCmsPlugin#363]
Hi,

is it possible to keep this plugin also available for Sylius 1.8.*? 

It's almost impossible to have a 1.9 as production with dependencies at the moment, a lot of plugins are not yet updated and the new features in this CMS Plugin are really interesting.

Thanks for considering

**Comment by GregoireDucharme** [comment]
Any news on this issue ?

**Comment by damonsson** [comment]
from 3.1.0 works on 1.8 also
