### ISSUE TITLE
Upgrading PHP8.0 and Symfony 5.2 for Sylius 1.9

### ISSUE THREAD

**Issue by netvlieshosting** [BitBagCommerce/SyliusCmsPlugin#366]
Hi,

Thank you guys for developing this plugin. It is a great implementation for a CMS feature in Sylius!

I was wondering though if this bundle will be compatible with PHP 8.0 and Symfony 5.2 in the near future. We are currently using this plugin in some of our E-commerce projects which we try to maintain with the latest Sylius, Symfony and PHP version. 
Could you provide any information regarding the roadmap of this plugin and when we can expect it to be PHP 8 compatible?

Thanks for considering in advance!

**Comment by damonsson** [comment]
Now it's compatible with PHP 8
