### ISSUE TITLE
[BC] Missing 3.0 upgrade instructions for Page images?

### ISSUE THREAD

**Issue by stefantalen** [BitBagCommerce/SyliusCmsPlugin#369]
While upgrading from 2.3.5 to 3.0.0 I noticed the Doctrine Migrations adds a query that will drop the `bitbag_cms_page_image` table.

This is because a Page uses a MediaInterface now (https://github.com/BitBagCommerce/SyliusCmsPlugin/pull/333).

Am I missing this significant change in the upgrade guide? Right now all my pages have no images anymore, it looks like I'll have to write a migration to transfer the data from the old table to the new structure.

**Comment by em411** [comment]
3.0 was a major update without backward compatibility for PageImages, which changed how the plugin stored PageImages. 

The easiest way to update your Pages is to download all images and add them again.

**Comment by stefantalen** [comment]
That's an easy way if you only have a few images, not 100+ 😉 

Given that it is a BC break, I still think it should have been mentioned in the upgrade document.

**Comment by em411** [comment]
Sorry for the late response, you're right :+1:
