### ISSUE TITLE
Blocks stop working 

### ISSUE THREAD

**Issue by GabrielAlmd** [BitBagCommerce/SyliusCmsPlugin#370]
Hello, I'm doing maintenance in a client server that is using block to create the home page.
Now when the client creates a new block or edits an existing one all blocks break, and even when I disable a block for a channel all channels turn off.
 How can I check what is the error in prod mode? 
The e-commerce that I'm editing it is using php v7.2, sylius v1.4, composer 2.0 and bitbag/cms-plugin v2.3, I now it is the old version but it's possivel to solve?

**Comment by damonsson** [comment]
Looks like problem with specific old version, fixed in newest versions.
