### ISSUE TITLE
Optional CKEditor

### ISSUE THREAD

**Issue by bitbager** [BitBagCommerce/SyliusCmsPlugin#39]
For now, we have the optional CKEditor guide in README file, but I think it would be nice to make an optional configuration and allow using it based on https://symfony.com/doc/current/bundles/IvoryCKEditorBundle/index.html.

**Comment by czende** [comment]
What about this one? https://github.com/froala/KMSFroalaEditorBundle
I'm using it in your bundle and its great :)

**Comment by bitbager** [comment]
Personally, I am a little bit afraid of using a bundle with `@TODO: write tests`. I used https://symfony.com/doc/master/bundles/IvoryCKEditorBundle/installation.html also with this plugin in a few projects (I also described how I installed it in the plugin README file) and was quite satisfied with it.

**Comment by czende** [comment]
@bitbager Yes, that's fail, but despite this its in my opinion one of the best wysiwyg editor nowaday. I've migrated from CKeditor and TinyMCE in all of my projects.

**Comment by bitbager** [comment]
What makes it better than CKEditor? 🙂

**Comment by bitbager** [comment]
As nobody got into any issues with the default WYSIWYG installation guide, I am closing this issue.
