### ISSUE TITLE
The parameter "bitbag_sylius_cms_plugin.model.block.class" must be defined.

### ISSUE THREAD

**Issue by stefanz92** [BitBagCommerce/SyliusCmsPlugin#394]
`composer require bitbag/cms-plugin`

Gives the following error on a clean Sylius 1.10 installation:

`Using version ^3.0 for bitbag/cms-plugin
./composer.json has been updated
Running composer update bitbag/cms-plugin
Loading composer repositories with package information
Updating dependencies
Lock file operations: 3 installs, 0 updates, 0 removals
  - Locking bitbag/cms-plugin (v3.0.7)
  - Locking friendsofsymfony/ckeditor-bundle (2.3.0)
  - Locking league/csv (9.7.1)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 3 installs, 0 updates, 0 removals
  - Installing league/csv (9.7.1): Extracting archive
  - Installing friendsofsymfony/ckeditor-bundle (2.3.0): Extracting archive
  - Installing bitbag/cms-plugin (v3.0.7): Extracting archive
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
140 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
phpstan/extension-installer: Extensions installed

Symfony operations: 2 recipes (260add7f175ebaa34dafcdab47205579)
  -  WARNING  friendsofsymfony/ckeditor-bundle (>=2.0): From github.com/symfony/recipes-contrib:master
    The recipe for this package comes from the "contrib" repository, which is open to community contributions.
    Review the recipe at https://github.com/symfony/recipes-contrib/tree/master/friendsofsymfony/ckeditor-bundle/2.0

    Do you want to execute this recipe?
    [y] Yes
    [n] No
    [a] Yes for all packages, only for the current installation session
    [p] Yes permanently, never ask again for this project
    (defaults to n): y
  - Configuring friendsofsymfony/ckeditor-bundle (>=2.0): From github.com/symfony/recipes-contrib:master
  - Configuring bitbag/cms-plugin (>=v3.0.7): From auto-generated recipe
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!   // Clearing the cache for the dev environment with debug                       
!!   // true                                                                        
!!  
!!  
!!  In FileLoader.php line 174:
!!                                                                                 
!!    The parameter "bitbag_sylius_cms_plugin.model.block.class" must be defined   
!!    in . (which is being imported from "/var/www/stor-e/vendor/sylius/sylius/sr  
!!    c/Sylius/Bundle/ApiBundle/Resources/config/routing.yml"). Make sure there i  
!!    s a loader supporting the "api_platform" type.                               
!!                                                                                 
!!  
!!  In App_KernelDevDebugContainer.php line 7103:
!!                                                                                 
!!    The parameter "bitbag_sylius_cms_plugin.model.block.class" must be defined.  
!!                                                                                 
!!  
!!  cache:clear [--no-warmup] [--no-optional-warmers]
!!  
!!  
Script @auto-scripts was called via post-update-cmd

Installation failed, reverting ./composer.json and ./composer.lock to their original content.`

**Comment by em411** [comment]
This error displays because Symfony Flex is clearing cache after executing any recipe. 
You need to add CMS plugin configuration, please, follow the entire installation instruction: https://github.com/BitBagCommerce/SyliusCmsPlugin/blob/master/doc/installation.md

**Comment by stefanz92** [comment]
Thanks for your comment.

The problem is that the first step in de installation instructions is to require bitbag/cms-plugin which is resulting in this error.
But ignoring the error and proceeding to the next steps and requiring bitbag/cms-plugin again seems to work.

Thanks!
