### ISSUE TITLE
Trying to install SyliusCmsPlugin

### ISSUE THREAD

**Issue by mathisang** [BitBagCommerce/SyliusCmsPlugin#395]
Hello,

I had install, yesterday, a Sylius project. Now i would like to install the CMS Plugin.

But when I'm trying : "composer require bitbag/cms-plugin"
I got this error : 
![screen](https://user-images.githubusercontent.com/41694248/138499573-52daa6ad-3324-4d59-87c4-93b5acee766c.png)

Could you help me please ?

Thanks

**Comment by jenyak** [comment]
Remove in `bundles.php`
```
FOS\CKEditorBundle\FOSCKEditorBundle::class => ['all' => true], // WYSIWYG editor
BitBag\SyliusCmsPlugin\BitBagSyliusCmsPlugin::class  => ['all' => true],
```
before executing `composer require bitbag/cms-plugin`

**Comment by gigamarr** [comment]
> 

I get the following error when do that
![2021-11-27-103142_435x122_scrot](https://user-images.githubusercontent.com/36007921/143670965-d777cad3-a399-4d88-8774-cd96d374909b.png)
