### ISSUE TITLE
Sitemap support

### ISSUE THREAD

**Issue by stefandoorn** [BitBagCommerce/SyliusCmsPlugin#41]
Sylius Sitemap Plugin exists: https://github.com/stefandoorn/sitemap-plugin. Would be great to have a provider to include the page URL's into it. 

Some options:
* Only provide a provider in this repo with tag `sylius.sitemap_provider` and add the sitemap plugin as a suggest to composer.json. And optionally put the activation behind a config setting.
* Provide functionality in a separate repo that requires both this package and the sitemap package + add the provider

@bitbager What do you prefer?

**Comment by bitbager** [comment]
Hmm, I think that generic sitemap provider functionality can be added to the plugin and an extra plugin for it would be too much. Would it be possible to write a sitemap processor and add the sitemap extension installation guide to the README file?

**Comment by stefandoorn** [comment]
If we put it behind a config setting, then we can dynamically load the service definition that includes the sitemap provider (which gives the URL's to the sitemap plugin). In that case the plugin also doesn't crash if users do not load the sitemap plugin. 

It would be weird to include it as requirement, as users then automatically get a sitemap also for products/taxons, etc. (not configurable yet). So it would be good to really activate it I think. WDYT about this?

**Comment by bitbager** [comment]
Yeap, looks like it would require another plugin. But it should not be hard to develop.

**Comment by stefandoorn** [comment]
Ok. I'll see if I can get it working inside the plugin first, else I'll go for a separate package.

**Comment by bitbager** [comment]
Perfect! Let me know once you make some progress 🙂

**Comment by bitbager** [comment]
@stefandoorn, any news? 🙂
