### ISSUE TITLE
Consider migrating to XML or annotation for entity mapping

### ISSUE THREAD

**Issue by Kazadri** [BitBagCommerce/SyliusCmsPlugin#421]
Hello; 

As the YamlDriver is deprecated and removed in doctrine/orm 3.0 :

> User Deprecated: YAML mapping driver is deprecated and will be removed in Doctrine ORM 3.0, please migrate to annotation or XML driver.

I can work on a PR if you want but witch one would you prefer ? Annotation or XML ?

Best regards;

**Comment by jakubtobiasz** [comment]
Hi 🙋🏻‍♂️!

This problem is not as hot as it may seem but I'd be great to keep the standard not only in our newest plugins :). In terms of plugins we're using `.xml` to define our configuration files. 

Thank you for opening this issue and your offer to help with migrating to `xml`. Cheers!

**Comment by Kazadri** [comment]
I've created the PR :)

During the migration to `xml` i've noticed some strange column name in join table (A pull request exist #400 )
Should I fix that in the same time ? (If I do that that mean there is a BC breaks since a migration will be required)

Cheers;

**Comment by senghe** [comment]
Hi @Kazadri, thanks for your PR. Unfortunately, we can't merge it now, as it makes a BC. But I'll tag the PR to be merged, when new major version will be released.

Regarding to xml - you're right, so I'm passing this on developers team :)

**Comment by MacBalc** [comment]
@senghe can column-name change be done? (linked with #400)
