### ISSUE TITLE
[Proposal] - Add preview column in media management list in admin. 

### ISSUE THREAD

**Issue by extrablind** [BitBagCommerce/SyliusCmsPlugin#424]
Hi ! 

Thanks for your work.
It could be interesting to add a preview column in admin media table list by default.
If it is an image => render image with imagine as fixed width or cropped to have predictable size in table.
If it is a file render a default image corresponding to mime type or a simple text.

What do you think ?

**Comment by Harvel218** [comment]
Hi, I think it's a good idea and it can be implemented, but I would like to clarify a few things.
The preview, should be more like in block/pages where you see real image in page, or just when you click "button" you receive some "popup" with preview, or this preview is always visible in some place on the page?

**Comment by extrablind** [comment]
@Harvel218 
I was talking about the list in media admin table. Your idea seems interesting too ;)
See picture below for clarification.
Explanation :
The basic need for media list is to actually see a preview of this media. I think it should be a default and should not require extra work to override template. For most people a name is not enough and frankly, almost nobody renames file before upload or take time to give a proper name in admin ;) 
The way you display it in any part of pages/website, should (in my opinion) be given to developer : for example using an liipimagine filter or keep it raw if needed
![image](https://user-images.githubusercontent.com/2227080/157553029-5b433a70-e952-4e33-81b6-4688378e2bbb.png)

Hope this is better definition of the proposal

**Comment by Vitallix** [comment]
This is easily done by adding a field to the grid Media, as well creating a template with an image, see an example on the Page grid .yml file.

**Comment by liszkapawel** [comment]
Added in #453 :)
