### ISSUE TITLE
Installation issue on Debian 11 with php8.0

### ISSUE THREAD

**Issue by fabrityzbigniewn** [BitBagCommerce/SyliusCmsPlugin#429]
Hi,
I want to add this plugin to my Sylius installation and have error like this:
`php bin/console sylius:theme:assets:install --symlink
Trying to install assets as symbolic links.

In Filesystem.php line 41:

  Failed to copy "/home/sylius/acme/vendor/api-platform/core/src/Bridge/Symfony/Bundle/Resources/public/es6-promis
  e/es6-promise.auto.min.js" because file does not exist.
`

Can I ask for help?

**Comment by damonsson** [comment]
Not related to our plugin, looks like OS problem or entire Sylius/Symfony.
