### ISSUE TITLE
`doctrine/dbal` and `doctrine/orm` conflict purpose ?

### ISSUE THREAD

**Issue by Geolim4** [BitBagCommerce/SyliusCmsPlugin#436]
Hello,

The Cms plugin is locking `doctrine/dbal` and `doctrine/orm` on old version, why ?

Doctrine fixed recently lot of bugs and I'm still stuck on Sylius 1.11 on 
```         
        "doctrine/orm": "^2.10",
        "doctrine/dbal": "^3.0",
``` 

Can you please up the requirements ? Those version are for some already unmaintained or will be soon and prevent us to upgrade things smoothly :(

Thank you.

**Comment by pierrecornic** [comment]
Hello,

We also have this issue. We were planning on using this plugin for our CMS but are already using a more recent version of Doctrine.

Thanks!

**Comment by gigamarr** [comment]
Part of the reason is that `doctrine/orm` 3.0 removed YAML mapping which this plugin is using. there's a PR open that you can try out https://github.com/BitBagCommerce/SyliusCmsPlugin/pull/422

**Comment by nrhuth** [comment]
Sylius is bumping version to 2.13
https://github.com/Sylius/Sylius/pull/14346

**Comment by pbalcerzak** [comment]
Hi! We have removed the `doctrine/orm` and `doctrine/dbal` conflict in #452

**Comment by Prometee** [comment]
Hello @pbalcerzak can we expect a new release ?
#452 is required to be able to install Sylius 1.11.9 with this plugin.

**Comment by Prometee** [comment]
@pbalcerzak thanks a lot 😉, it's working now :
![image](https://user-images.githubusercontent.com/861820/193798659-bc2fa551-0ea2-4f76-a067-7af70da7f61b.png)
