### ISSUE TITLE
[feedback]Unify and fix the asset paths on how to properly install plugins without Webpack

### ISSUE THREAD

**Issue by Ferror** [BitBagCommerce/SyliusCmsPlugin#447]
Each of the plugins has different paths to the CSS and JS files. Let's unify them and make the configuration up to date.

<img width="379" alt="Screenshot 2022-08-24 at 19 32 40" src="https://user-images.githubusercontent.com/17534504/186485446-961b99f1-0318-42f0-b25c-b2215c76a98d.png">

**Comment by stefandoorn** [comment]
It seems that the docs here point to the wrong locations as well: https://github.com/BitBagCommerce/SyliusCmsPlugin/blob/master/doc/01.5-non-webpack.md

**Comment by pbalcerzak** [comment]
Thanks! Readme updated in #450
