### ISSUE TITLE
[feedback]Stop autoloading tests

### ISSUE THREAD

**Issue by Ferror** [BitBagCommerce/SyliusCmsPlugin#448]
Autoloading tests have a negative impact on application performance and it is a bad practice. The `Tests\\BitBag\\SyliusCmsPlugin` should be autoload-dev

## Now
```json
{
    "autoload": {
        "psr-4": {
            "BitBag\\SyliusCmsPlugin\\": "src/",
            "Tests\\BitBag\\SyliusCmsPlugin\\": "tests/" 
        }
    },
}
```

## Should be
```json
{
    "autoload": {
        "psr-4": {
            "BitBag\\SyliusCmsPlugin\\": "src/" 
        }
    },
}
```

**Comment by senghe** [comment]
Thanks for your feedback @Ferror. It seems to be something worth to be checked in all our plugins.

Will be back, when it's implemented 👍

**Comment by pbalcerzak** [comment]
Hi @Ferror, based on https://github.com/Sylius/PluginSkeleton/issues/174 the Behat tests have to be autoloaded for others to reuse our contexts. We decided not to make any changes

**Comment by Ferror** [comment]
Alright. Therefore it should be. Still loading Behat Contexts and loading whole unit tests etc makes difference

```
{
    "autoload": {
        "psr-4": {
            "BitBag\\SyliusCmsPlugin\\": "src/" ,
            "Tests\\BitBag\\SyliusCmsPlugin\\Behat\\": "tests/Behat/" 
        }
    },
}
```
