### ISSUE TITLE
Available for sylius 1.12

### ISSUE THREAD

**Issue by qhayat** [BitBagCommerce/SyliusCmsPlugin#455]
Hello,

Thank you for everything you do.

Soon a capability with sylius 1.12?

Best regard

**Comment by senghe** [comment]
Hi @qhayat, 

> Thank you for everything you do.

No problem :)

> Soon a capability with sylius 1.12?

Yes, we are working currently on upgrading our plugins to Sylius 1.12. I'll be back to you when have more details :)

**Comment by qhayat** [comment]
Hi @senghe,

Thanks.

see you soon :)

**Comment by datbachkhoa** [comment]
Hi @senghe,

Could you tell me when this plugins will be available for Sylius 1.12?

**Comment by anthonyhexium** [comment]
Any update here ?

**Comment by hmonglee** [comment]
https://github.com/BitBagCommerce/SyliusCmsPlugin/releases/tag/v3.3.0

**Comment by JulienLoison** [comment]
> https://github.com/BitBagCommerce/SyliusCmsPlugin/releases/tag/v3.3.0

This tag is 7 commits behind master and does not include 1.12 support

Maybe @senghe can look into it ?

**Comment by hmonglee** [comment]
> > https://github.com/BitBagCommerce/SyliusCmsPlugin/releases/tag/v3.3.0
> 
> This tag is 7 commits behind master and does not include 1.12 support
> 
> Maybe @senghe can look into it ?

my bad, miss read, thank you

**Comment by baatarchuluun** [comment]
When I'm trying to install: 
```
 Problem 1
    - Root composer.json requires bitbag/cms-plugin ^3.3 -> satisfiable by bitbag/cms-plugin[v3.3.0].
    - bitbag/cms-plugin v3.3.0 requires sylius/sylius ~1.8.0 || ~1.9.0 || ~1.10.0 || ~1.11.0 -> found sylius/sylius[v1.8.0-RC.1, ..., 1.11.x-dev] but it conflicts with your root composer.json require (^1.12).
```

**Comment by JulienLoison** [comment]
@baatarchuluun You can use bitbah/cms-plugin:dev-master while we wait for the plugin to be correctly tagged

**Comment by damonsson** [comment]
Support 1.12 into release [4.0](https://github.com/BitBagCommerce/SyliusCmsPlugin/releases/tag/v1.4.0)
