### ISSUE TITLE
Twig parser error when rendering page or directing to page

### ISSUE THREAD

**Issue by Tsolmonx** [BitBagCommerce/SyliusCmsPlugin#460]
BitBag\SyliusCmsPlugin\Twig\Parser\ContentParser::__construct(): Argument #1 ($twigEnvironment) must be of type Twig_Environment, Twig\Environment given, called in /Users/tsolmonkhorloo/phpstormprojects/easystore-sylius-basic/var/cache/dev/ContainerZxvRmAw/getBitbagSyliusCmsPlugin_Twig_Runtime_RenderContentService.php on line 31

i got this error when i 
    {{ render(path('bitbag_sylius_cms_plugin_shop_page_show_link_by_code', {'code' : 'about', 'template' : '@BitBagSyliusCmsPlugin/Shop/Page/Show/_link.html.twig'})) }}
 jump to the page through this code.

**Comment by hmonglee** [comment]
Fixed with this PR https://github.com/BitBagCommerce/SyliusCmsPlugin/pull/459
