### ISSUE TITLE
Translations not loading

### ISSUE THREAD

**Issue by machraf** [BitBagCommerce/SyliusCmsPlugin#468]
Translations not loading after installation, am I missing something?

Context:
Language code is en
Sylus 1.12
PHP 8.1

![Screenshot from 2023-03-02 14-33-02](https://user-images.githubusercontent.com/58884843/222443310-50ceacc1-df9a-4c5f-b9c4-d9a64e84cabc.png)

**Comment by rafalmal** [comment]
I believe that if the plugin is properly installed, clearing the cache should help

**Comment by machraf** [comment]
Clearing the cache helped, thanks @rafalmal.

**Comment by rafalmal** [comment]
I'm glad I could help
