### ISSUE TITLE
No image shown in Page even tho i  have images in media

### ISSUE THREAD

**Issue by Tsolmonx** [BitBagCommerce/SyliusCmsPlugin#469]
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/108046456/222953672-1b8a7faf-a4b8-4afc-9815-cc448d226ee4.png">

**Comment by MuGGYStyle** [comment]
@Tsolmonx you should manually configure web config
 https://github.com/BitBagCommerce/SyliusCmsPlugin/blob/master/doc/01.1-webpack-config.md

**Comment by liszkapawel** [comment]
Hello @Tsolmonx,
Did you manage to solve the problem?
