### ISSUE TITLE
Sections URL should not be generated in sitemap

### ISSUE THREAD

**Issue by David-Crty** [BitBagCommerce/SyliusCmsPlugin#473]
Because of [this file](https://github.com/BitBagCommerce/SyliusCmsPlugin/blob/master/src/Resources/config/services/sitemap_provider.yml), we are generating a `cms_sections` XML sitemap with URLs like `/{_locale}/section/{code}`. 
When you try to access the URL, you get a 500 because there is no `$template` variable. You get an error like `Unable to find template "/show.html.twig" (looked into: /app/vendor/knplabs/knp-menu/src/Knp/Menu/Resources/views, /app/templates, /app/templates, /app/vendor/symfony/twig-bridge/Resources/views/Form).`

IMHO, we should not generate section URLs in the sitemap, as [the doc says](https://github.com/BitBagCommerce/SyliusCmsPlugin/blob/master/doc/sections.md). The sections look to be rendered using TWIG, e.g.: `{{ render(path('bitbag_sylius_cms_plugin_shop_block_index_by_section_code', {'sectionCode' : 'blog', 'template' : '@BitBagSyliusCmsPlugin/Shop/Block/index.html.twig'})) }}`

I could make a PR removing the URL section generation in the sitemap; what do you think?

For now, to avoid thous URLs to be added in the sitemap, I did a `$container->removeDefinition('bitbag_sylius_cms_plugin.sitemap_provider.section'); `

**Comment by MacBalc** [comment]
@David-Crty could you take a look at PR i have prepped? Is this something addressing your issue?

**Comment by David-Crty** [comment]
> @David-Crty could you take a look at PR i have prepped? Is this something addressing your issue?

Yes this will fix the issue, thanks for your PR :heart:
