### ISSUE TITLE
WYSIWYG image with AWS

### ISSUE THREAD

**Issue by t-n-y** [BitBagCommerce/SyliusCmsPlugin#478]
Is there a way to display images in the wysiwyg with aws images ?

I can't find a way to display the images when i upload one directly from my computer. The image is sended well on aws, but then the image look like this `<img alt="" src="f0/78/1bf777a6d93c68b3b3012219e9dc.png"` and of course the link is not good, because it is stored on aws.

Thanks for the help

**Comment by senghe** [comment]
Hi @t-n-y , thanks for the isssu.

Currently the plugin doesn't support any kind of CDNs from scratch. From my perspective, the first what I'm thinking about is that  you should try to prefix the paths in your content with your CDN domain in specified form type/extension on before data is set event, and then remove the prefix from the content on before submit event.

I'm closing this now, as we currently doesn't plan to support any CDNs.
