### ISSUE TITLE
CMS pages: call template from Admin Content field

### ISSUE THREAD

**Issue by anitr** [BitBagCommerce/SyliusCmsPlugin#483]
Hi,

I am new to Sylius and new to SyliusCMSPlugin. I created a CMS page and I wonder if it is possible to call a template inside Content field, for example:

{% include '@SyliusShop/Homepage/_latestNews.html.twig' %}

or with any other way?

**Comment by senghe** [comment]
Hi, by default you cannot do this. But if you really need it, please play with `https://github.com/BitBagCommerce/SyliusCmsPlugin/blob/master/src/Twig/Parser/ContentParser.php` class and the `%bitbag_cms.twig.admin_functions%` parameter.
