### ISSUE TITLE
CKEditor 4 LTS usage or CKEditor 5

### ISSUE THREAD

**Issue by stefandoorn** [BitBagCommerce/SyliusCmsPlugin#485]
Hi,

Related to this https://github.com/FriendsOfSymfony/FOSCKEditorBundle/issues/253 & https://ckeditor.com/ckeditor-4-support/, I guess for many users CKEditor 4 is becoming difficult to use. 

It might be time to upgrade to CKEditor 5, but I'm not sure how straightforward the upgrade process is..

**Comment by michaelKaefer** [comment]
As long as the bundle is not using ckeditor 5 there is an easy workaround is described in: https://github.com/FriendsOfSymfony/FOSCKEditorBundle/issues/253.

**Comment by crmn-frws** [comment]
it's not just "difficult" ;) 
we either can't use it anymore (broken ckeditor with error 'invalid lts-license-key' in devtools) or have to buy a license for LTS. @michaelKaefer's workaround works

**Comment by senghe** [comment]
Hi all, thanks for your comments.

I have already tested the `4.22.1` tag and it works good. I've updated the installation docs, including a note regarding to this issue.

**Comment by markbeazley** [comment]
Not sure if this is needs to be a new issue or this one reopened, but it seems they have started pushing a big error message if you are using 4.22.1

![image](https://github.com/BitBagCommerce/SyliusCmsPlugin/assets/17005579/09656676-ccd5-4ddf-8c15-712dfe3b9a93)
