### ISSUE TITLE
Error: Requested page is invalid.

### ISSUE THREAD

**Issue by maxby** [BitBagCommerce/SyliusCmsPlugin#58]
When I change path pattern for product's taxon - plugin is crashing(
Step to reproduce:
1. Open file #sylius/src/Sylius/Bundle/ShopBundle/Resources/config/routing/product.yml
2. Change default path pattern from "path: /taxons/{slug}" to "path: /{slug}"
3. Profit( On admin side and front error is same

**Comment by maxby** [comment]
I found solution.
You need insert plugin rout before sylius_shop in file #sylius/app/config/routing.yml

**Comment by bitbager** [comment]
Looks like you customized your instance to have two routes that request two different controllers 🙂
