### ISSUE TITLE
https don't have permission to access /admin/blocks/new/html on this server

### ISSUE THREAD

**Issue by benyang2015** [BitBagCommerce/SyliusCmsPlugin#66]
use https://www.xxx.com display you don't have permission to access when save the block
what happen!

**Comment by bitbager** [comment]
Sorry, I don't understand your problem. Our plugin does not depend on HTTP version and from what I understand, it seems like you have a problem with permissions on your server.

**Comment by benyang2015** [comment]
I set the file to 777，also get this error

**Comment by benyang2015** [comment]
I select the block type about html,the content input html code and save it display the permission
input test can work fine

**Comment by bitbager** [comment]
Can you attach some screenshots of the steps required to reproduce this issue? Or maybe if you are able to do it, Behat scenario would be perfect 😉

**Comment by benyang2015** [comment]
the code like this can work:![image](https://user-images.githubusercontent.com/15188607/32473403-649f23ac-c3a2-11e7-996c-c7929cfde687.png)

this display the error about permission:
![image](https://user-images.githubusercontent.com/15188607/32473455-900590e4-c3a2-11e7-8ca8-3fd104510ca9.png)
![image](https://user-images.githubusercontent.com/15188607/32473467-9e7b6a54-c3a2-11e7-8ba0-a8303620784a.png)
