### ISSUE TITLE
Pages Select Products and Sections

### ISSUE THREAD

**Issue by TELLO0815** [BitBagCommerce/SyliusCmsPlugin#97]
There are not products or prepared sections in the select-menu.
Endless AJAX requests.

As example:
```
GET | xhr | 200 | /app_dev.php/admin/ajax/products/search?phrase=&_=1510959359857 | 667ms | 4596d2
-- | -- | -- | -- | -- | --
GET | xhr | 200 | /app_dev.php/admin/ajax/products/search?phrase=&_=1510959359856 | 267ms | 5d0764
GET | xhr | 200 | /app_dev.php/admin/ajax/products/search?phrase=&_=1510959359855 | 250ms | bacf43
GET | xhr | 200 | /app_dev.php/admin/ajax/products/search?phrase=&_=1510959359854 | 285ms | 04b45c
GET | xhr | 200 | /app_dev.php/admin/ajax/products/search?phrase=&_=1510959359853 | 353ms | 02da46
GET | xhr | 200 | /app_dev.php/admin/ajax/products/search?phrase=&_=1510959359852 | 244ms | e76459
GET | xhr | 200 | /app_dev.php/admin/ajax/products/search?phrase=&_=1510959359851 | 320ms | cd5d1d
GET | xhr | 200 | /app_dev.php/admin/ajax/products/search?phrase=&_=1510959359850 | 255ms | 0fc0
```

Any idea?
Mike

**Comment by bitbager** [comment]
@patrick477, any idea?

**Comment by bitbager** [comment]
As far as I am concerned, these requests are made on the keyup event in the products/sections association form field. From what I can see, they're referring to specific phrases. Are you typing them in the form field?

**Comment by TELLO0815** [comment]
If i type them in - nothing found. (No results found.) When i press the arrow - endless request.

**Comment by benyang2015** [comment]
on the backend，admin user use the en_US language? if not, it will display no results found

**Comment by TELLO0815** [comment]
@benyang2015 , no i don't use en_US at all. de_CH is what the Admin reads.

**Comment by benyang2015** [comment]
you can set the admin language to en_US,select the product you want,the set the admin language to de_CH

**Comment by benyang2015** [comment]
update to cmsplugin 1.2.2,can not select product and Sections!
display not result to find

**Comment by bitbager** [comment]
@damonsson, @shinoks, could you guys give it a look?

**Comment by gnsimoes** [comment]
Hello,

I have the same problem!
I am using pt_PT language as a primary language on my system. When I want to select a section on block or page admin view, the background scripts cannot find any data.
The reason is because it is hardcoded on DI as en language, so you will never get any data at all. If try to see the profiler you will find the queries with language filter with "en".

It would be better the DI could get the system or the user session language...

**Comment by bitbager** [comment]
Could you provide a PR with Behat scenario?

**Comment by thelegendtwentyseven** [comment]
Channel locale is set to "nl" and when admin language is not set to "nl" it can't find sections or products in the page edit screen. Will this be fixed?

**Comment by kor3k** [comment]
I also confirm this. when admin user's locale differs from channel default locale, the product & section loaders cannot find anything

**Comment by damonsson** [comment]
@thelegendtwentyseven Sure, we'll check and try fix it in the coming days cause we see that a lot of people have a problem with it
